# 第七章

## 7.1 处理错误

- Throwable
  	├─ Error
	└─ Exception
			├─ RuntimeException
			└─ 其他Exception

- RuntimeException ：由程序错误导致的异常，（程序员全责）

   - 错误的类型转换
   - 数组越界
   - 空指针

- 非 RuntimeException

   - 试图在文件尾部后面继续读文件
   - 试图打开一个不存在的文件

- Java 语言规范将派生于Error 类 或 RuntimeException 类的所有异常称为非受查( unchecked ) 异常，所有其他的异常称为受查(checked) 异常。

   - 编译器将核查是否为所有的**受査异常**提供了异常处理器

- 当方法内发生下列情况时，方法上必须 抛出异常

   - 调用一个抛出受査异常的方法， 例如， FilelnputStream 构造器。
   - 程序运行过程中发现错误， 并且利用 throw语句抛出一个受查异常

- 不需要声明 Java 的内部错误（即从 Error 继承的错误）。也不应该声明从 RuntimeException 继承的那些非受查异常

- 如果在子类中覆盖了超类的一个方法， 子类方法中声明的受查异常不能比超类方法中声明的异常更通用

- 方法中真实抛出的异常，有可能是 声明抛出异常 的子类异常

- 使用 **throw** 关键字抛出异常

- 在程序中，可能会遇到任何标准异常类都没有能够充分地描述清楚的问题。 在这种情况下，**创建自己的异常类**就是一件顺理成章的事情了。

   我们需要做的只是定义一个派生于Exception 的类，或者派生于 Exception 子类的类。习惯上， 定义的类应该包含**两个构造器**， 一个是**默认的构造器**；另一个是**带有详细描述信息的构造器**（超类 Throwable 的 **toString 方法**将会打印出这些详细信息， 这在调试中非常有用)

## 7.2 捕获异常

- 带资源的 try 语法

  ```java
  try (Scanner in = new Scanner(new FileInputStream("7usr/share/dict/words"), "UTF-8");
       PrintWriter out = new PrintWriter("out.txt"))
  {
      while (in.hasNext()) 
          out.println(in.next().toUpperCase());
  }catch (Exception e) {
      // TODO: handle exception
  }
  ```

  这样的话，等同于在 finally中 close 了 in 和 out 两个资源

- 堆栈轨迹（ **stack** **trace** ) 是一个方法调用过程的列表

## 7.3 使用断言

- 在程序中会有很多地方对参数有**心理预期**（比如Math.sqtr(x) x 希望是正数），然而我们编码时，都不能每个地方都抛出 异常，那样运行起来，速度很慢，所以使用 asser 断言
- 两种格式
  - assert 条件
  - assert 条件：表达式